---
# tasks file for openstack-keypair
- name: Generate key files
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/cho_id_rsa

- name: delete_exist_os_keypair
  os_keypair:
    auth: "{{ os_auth }}"
    state: absent
    name: cho_ssh

- name: create_os_keypair
  os_keypair:
    auth: "{{ os_auth }}"
    state: present
    name: cho_ssh
    public_key_file: "{{ ansible_env.HOME }}/.ssh/cho_id_rsa.pub"
